import React from 'react'

const PrivacyPolicy = () => {
  return (
    <div className='mx-auto  p-5 md:p-10 max-w-3xl'>
      <h1 className='font-semibold text-2xl md:text-3xl mb-5'>Privacy Policy</h1>
      <p className='text-md md:text-lg leading-relaxed'>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4'>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations and privacy policy for access or usage of www.sparindia.com website and mobile app ("Website").
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4'>
        Max Hypermarket India Private Limited, a Company incorporated in India under the provisions of Companies Act, 1956 having its corporate office at First floor (Above SPAR), No. 39/3 & 44, Bannerghatta Road Bangalore 560029, Karnataka (referred to herein as "Max Hypermarket", "SPAR", "sparindia.com", "we", "our" or "us") operates the Internet e-commerce website www.sparindia.com (or any successor site) and its related sub-domains, sites, Services and tools ("Website"). The Website is provided as a service to user and is intended to allow users to browse and order products and other goods or services ("Products") offered for sale on the Website ("Services"). We are committed to protecting your privacy online. This privacy policy (the "Privacy Policy") discloses the privacy practices for the Website and Participating Website (currently comprising of www.sparindia.com, and their related sub-domains, sites, services and tools, or any successor site (jointly or severally referred as "Participating Website", as the context so require) and or affiliate or group companies of Max Hypermarket. The number of Participating Website may also vary in the course of time. This Privacy Policy describes the ways in which we collect, store, use and protect the information collected due to your use of Website. By accessing the Website and/or providing us with your information you expressly consent to us processing your personal information in accordance with the terms of the Privacy Policy. We reserve the right to delete, modify, change or supplement the content of the Website and or this Privacy Policy at any time for any reason without prior notification, and will use reasonable efforts to include up-to-date and accurate information on the Website.
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4'>
        PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY ACCESSING OR USING OUR WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO THE TERMS OF THIS PRIVACY POLICY.
      </p>
    </div>
  )
}

export default PrivacyPolicy