import React from 'react'

const Terms = () => {
  return (
    <div className='mx-auto px-5 md:p-10 max-w-3xl'>
      <h1 className='text-2xl md:text-3xl font-semibold my-5'>Terms & Policies</h1>
      <p className='text-md md:text-lg leading-relaxed'>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4'>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.sparindia.com website.
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4'>
        Max Hypermarket India Private Limited, a Company incorporated in India under the provisions of Companies Act, 1956 (referred to herein as 'Max Hypermarket', "SPAR", "sparindia.com", "we", "our" or "us") operates the Internet e-commerce website www.sparindia.com (or any successor site) and its related sub-domains, sites, Services and tools ("Website"). The Website is provided as a service to user and is intended to allow users to browse and order products and other goods or services ("Products") offered for sale on the Website ("Services"). SPAR reserves the right to delete, modify, or supplement the content of the Website at any time for any reason without prior notification, and will use reasonable efforts to include up-to-date and accurate information on the Website.
      </p>
      <p className='text-md md:text-lg leading-relaxed mt-4 font-bold'>
        NOTWITHSTANDING ANY ORAL OR WRITTEN INFORMATION, OPINIONS, EVALUATIONS, DESCRIPTIONS OR CONSULTATIONS OF ANY KIND FURNISHED BY SPAR TO THE CONTRARY, USER SPECIFICALLY AGREES TO THE TERMS SET FORTH BELOW.
      </p>
    </div>
  )
}

export default Terms